---
title: 'fieldwalkr: an R package for spatial sampling and field survey simulation'
author: "Joe Roe (University of Copenhagen) <jwg983@hum.ku.dk>"
date: "19 September 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Paper presented at the 2018 Landscape Archaeology Conference, Newcastle & Durham,
in Session 44C, *Landscape Archaeology and Reproducible Research*

## Introduction

## From reproducibility to replicibility in landscape archaeology

Daniel has already talked about the recent explosion of interest in (or concern about!) reproducibility in science.
In archaeology, I think we've come a long way in a very short time:
just a couple of years ago you were lucky to find a single line of code or a formula in a paper;
now we have people like Ben Marwick publishing research on GitHub as full-fledged literate programming documents,
or the ISAAK group in Kiel writing open R packages specifically for archaeologists.

But 'reproducibility' is the tip of the iceburg: "a minimal attainable standard"
    * Terminological confusion (some switch reproducibility and replicability, or distinguish between e.g. "computational reproducibility", "methodological reproducibility", and "inferential reproducibility")
    * But I don't think that's very important. 
      The point is, open science = good science.
      The further down the iceburg we can push reproducibility,
* 

## Spatial sampling in archaeology

## `fieldwalkr`

* Purpose: simulating archaeological surveys
    * Make more informed decision about sampling strategy (no longer a stab the dark)
    * Explore the "parameter space"
    * Analysis the effect of sampling post-hoc; what if I'd done it differently?
* Framework: archaeological survey modelled as three components:
    * Point process
    * Sampling frame
    * Detection function
* Implementation: why R? why tidyverse? why shiny?

## Demonstration

Here I give a basic introduction to `fieldwalkr`, covering:

* Randomly generating survey frames using `rpolygon()`
* (point patterns)
* Survey units: `mosaic()`, `gridded()` and `transects()`
* Sampling strategies: `random()` and `systematic()`
* (detection functions)
* Simulation with `survey()`
* Comparing simulated results with the original point pattern
* Building survey pipelines for sensitivity analysis

## Current status and future plans
